name: Auto PR Review

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number'
        required: true

env:
  RUNPOD_API_TOKEN: ${{ secrets.RUNPOD_API_TOKEN }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub Requests boto3
    - name: Configure AWS SSO Credentials
      env:
        AWS_SSO_START_URL: ${{ secrets.AWS_SSO_START_URL }}
        AWS_SSO_REGION: ${{ secrets.AWS_SSO_REGION }}
        AWS_SSO_ACCOUNT_ID: ${{ secrets.AWS_SSO_ACCOUNT_ID }}
        AWS_SSO_ROLE_NAME: ${{ secrets.AWS_SSO_ROLE_NAME }}
      run: |
        aws --version
        aws configure set sso_start_url $AWS_SSO_START_URL
        aws configure set sso_region $AWS_SSO_REGION
        aws configure set sso_account_id $AWS_SSO_ACCOUNT_ID
        aws configure set sso_role_name $AWS_SSO_ROLE_NAME
        aws configure sso-session sso_session
        aws sso login --profile sso_profile
    - name: Review PR
      id: prompt-step
      env:
        AWS_PROFILE: sso_profile
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.inputs.prNumber }}
      run: |
        python auto_review_files/get_github_changes.py
