name: Auto PR Review

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number'
        required: true

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub Requests

    - name: Formulate Prompt
      id: prompt-step
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.inputs.prNumber }}
      run: |
        echo "prompt=${python auto_review_files/get_github_changes.py}"  >> $GITHUB_OUTPUT
    - name: Print Prompt
      run : |
        echo "HERE IS THE PROMPT"
        echo ${{ steps.prompt-step.outputs.prompt }}
