name: Auto PR Review

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number'
        required: true

env:
  RUNPOD_API_TOKEN: ${{ secrets.RUNPOD_API_TOKEN }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Configure Poetry
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub Requests litellm
    - name: Run Proxy Server
      run: |
        poetry install --all-extras
        poetry run runpod-ollama start-proxy &
        sleep 5
    - name: Formulate Prompt
      id: prompt-step
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.inputs.prNumber }}
      run: |
        python auto_review_files/get_github_changes.py
        prompt=$(python auto_review_files/get_github_changes.py | sed "s/\`//g")
        encoded_prompt=$(echo "$prompt" | base64)
        
        echo "prompt<<EOF" >> $GITHUB_OUTPUT
        echo "$prompt" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    # - name: Print Prompt
    #   env:
    #     PROMPT: "${{ steps.prompt-step.outputs.prompt }}"
    #   run : |
    #     prompt="${{ steps.prompt-step.outputs.prompt }}"
    #     echo "$prompt"

